### ISSUE TITLE
Error while communicating with OpenAI

### ISSUE THREAD

**Issue by vincentmakayama** [Doriandarko/o1-engineer#8]
I sent one short instruction and got this error:

> Error while communicating with OpenAI: Completions.create() got an unexpected keyword argument 'max_completion_tokens'

There are enough credits in my OpenAI API account.

**Comment by vincentmakayama** [comment]
The issue was closed by @Doriandarko without answering the question, but I figured it out myself. OpenAI only allows heavy users (= payers) access to version o1 via the API. So called ´Tier 5´ customers. For us mortal souls, it´s not accessible. Would be nice if a warning was added to the readme of o1-engineer. Other than that, I found the code does not seem to work via the regular Mac Terminal, but needs Visual Studio Code from Microsoft to run properly. The same counts for Claude Engineer, the sister project of this one.

**Comment by HeyitsRadinn** [comment]
This has been changed, it is now available to Tier 3 and above

> The issue was closed by @Doriandarko without answering the question, but I figured it out myself. OpenAI only allows heavy users (= payers) access to version o1 via the API. So called ´Tier 5´ customers. For us mortal souls, it´s not accessible. Would be nice if a warning was added to the readme of o1-engineer. Other than that, I found the code does not seem to work via the regular Mac Terminal, but needs Visual Studio Code from Microsoft to run properly. The same counts for Claude Engineer, the sister project of this one.
